version: "3.8"

services:
  app:
    build: .
    container_name: todo-app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: todo-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

volumes:
  postgres_data:
