name: CI Workflow

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd "pg_isready -U postgres -d postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      APP_NAME: "Task Management API"
      API_V1_STR: "/api/v1"
      ASYNC_DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres:5432/postgres"
      SYNC_DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
      DESCRIPTION: "API for managing tasks and users"
      DEBUG: False
      APP_HOST_PORT: 8080
      MODE: TEST

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Кэширование зависимостей
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Обновление pip
        run: pip install --upgrade pip

      - name: Установка зависимостей
        run: pip install -r requirements.txt

      - name: Ожидание PostgreSQL
        run: |
          for i in {1..10}; do
            pg_isready -h postgres -p 5432 && echo "DB is ready" && exit 0
            echo "Waiting for DB..."
            sleep 3
          done
          echo "DB did not become available in time" && exit 1

      - name: Применение миграций
        env:
          SYNC_DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
        run: alembic upgrade head

      - name: Запуск тестов
        run: pytest tests/test_api.py --disable-warnings
